server:
  port: 8088

spring:
  application:
    name: product-service
  cloud:
    config:
      enabled: true

  datasource:
    url: jdbc:mysql://product-db:3306/productdb?createDatabaseIfNotExist=true
    username: root
    password: gmbaloch123$
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
